include:
  - project: 'platform-one/big-bang/pipeline-templates/pipeline-templates'
    ref: pipeline-nonibimages
    file: '/templates/package-tests.yml'
variables:
  DEPENDENCY_REPO: "https://repo1.dsop.io/platform-one/big-bang/apps/core/istio-operator.git"
  DEPENDENCY_REPO_BRANCH: add-pipeline
  ISTIO_GATEWAY_NS: istio-system
  ADD_NAMESPACE: ["istio-system"]
    
   
