include:
  - project: 'platform-one/big-bang/pipeline-templates/pipeline-templates'
    ref: istio-test
    file: '/templates/package-tests.yml'
variables:
  PACKAGE_NAMESPACE: istio-system
  PACKAGE_HELM_NAME: istio
