apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jaeger
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "tracing.{{ .Values.hostname }}"
  gateways:
  - "{{ .Release.Namespace }}/main"
  http:
  - route:
    - destination:
        port:
          number: {{ .Values.ingress.jaeger.port | default "80" }}
        host: {{ .Values.ingress.jaeger.service }}.{{ .Values.ingress.jaeger.namespace | default .Release.Namespace }}.svc.cluster.local
