{{- if not .Values.sso.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "kiali.{{ .Values.hostname }}"
  gateways:
  - main.{{ .Release.Namespace }}.svc.cluster.local
  http:
  - route:
    - destination:
        port:
          number: 20001
        host: {{ .Values.ingress.kiali.service }}.{{ .Values.ingress.kiali.namespace  | default "{{ .Release.Namespace}}" }}.svc.cluster.local
{{- end }}
