apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "kiali.{{ .Values.hostname }}"
  gateways:
  - "{{ .Release.Namespace }}/main"
  http:
  - route:
    - destination:
        port:
          number: {{ .Values.ingress.kiali.port | default "20001" }}
        host: {{ .Values.ingress.kiali.service }}.{{ .Values.ingress.kiali.namespace | default .Release.Namespace }}.svc.cluster.local
